---
title: "USN-2469-2&#58; Django regression"
series: [ ubuntu-10.04-lts]
date: 2015-02-04 12:00:00
description: |
    USN-2469-1 fixed vulnerabilities in Django. The security fix for [CVE-2015-0221](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2015-0221) introduced a regression on Ubuntu 10.04 LTS and Ubuntu 12.04 LTS when serving static content through GZipMiddleware. This update fixes the problem.
--- 
 
 

*04 February 2015*

### python-django regression

A security issue affects these releases of Ubuntu and its derivatives:

* Ubuntu 12.04 LTS
* Ubuntu 10.04 LTS

### Summary

USN-2469-1 caused a regression in Django. 

### Software description

* python-django 

### Details

USN-2469-1 fixed vulnerabilities in Django. The security fix for [CVE-2015-0221](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2015-0221) introduced a regression on Ubuntu 10.04 LTS and Ubuntu 12.04 LTS when serving static content through GZipMiddleware. This update fixes the problem.

We apologize for the inconvenience.

Original advisory details:

 Jedediah Smith discovered that Django incorrectly handled underscores in WSGI headers. A remote attacker could possibly use this issue to spoof headers in certain environments. ([CVE-2015-0222](http://people.ubuntu.com/~ubuntu-security/cve/CVE-2015-0219">CVE-2015-0219</a>) Mikko Ohtamaa discovered that Django incorrectly handled user-supplied redirect URLs. A remote attacker could possibly use this issue to perform a cross-site scripting attack. (<a href="http://people.ubuntu.com/~ubuntu-security/cve/CVE-2015-0220">CVE-2015-0220</a>) Alex Gaynor discovered that Django incorrectly handled reading files in django.views.static.serve(). A remote attacker could possibly use this issue to cause Django to consume resources, resulting in a denial of service. (<a href="http://people.ubuntu.com/~ubuntu-security/cve/CVE-2015-0221">CVE-2015-0221</a>) Keryn Knight discovered that Django incorrectly handled forms with ModelMultipleChoiceField. A remote attacker could possibly use this issue to cause a large number of SQL queries, resulting in a database denial of service. This issue only affected Ubuntu 14.04 LTS and Ubuntu 14.10. (<a href="http://people.ubuntu.com/~ubuntu-security/cve/CVE-2015-0222)) 

### Update instructions

The problem can be corrected by updating your system to the following package version:

Ubuntu 12.04 LTS
 : [python-django](https://launchpad.net/ubuntu/+source/python-django) <span> [1.3.1-4ubuntu1.15](https://launchpad.net/ubuntu/+source/python-django/1.3.1-4ubuntu1.15) </span> 

Ubuntu 10.04 LTS
 : [python-django](https://launchpad.net/ubuntu/+source/python-django) <span> [1.1.1-2ubuntu1.16](https://launchpad.net/ubuntu/+source/python-django/1.1.1-2ubuntu1.16) </span> 

To update your system, please follow these instructions: [https://wiki.ubuntu.com/Security/Upgrades](https://wiki.ubuntu.com/Security/Upgrades).

In general, a standard system update will make all the necessary changes. 

### References

 
 [LP: 1417274](https://launchpad.net/bugs/1417274)
 

